trigger:
  branches:
    include:
      - dev
      - test
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Terraform_Plan
  displayName: 'Terraform Plan'

  jobs:
  - job: TerraformPlan

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.9.8'

    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: 'Azure subscription 1 (b7a31e2a-65b9-4c9d-90df-6dc6a8301e24)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd terraform

          terraform version

          terraform init -input=false

    - task: AzureCLI@2
      displayName: 'Terraform Validate'
      inputs:
        azureSubscription: 'Azure subscription 1 (b7a31e2a-65b9-4c9d-90df-6dc6a8301e24)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd terraform

          terraform validate

    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: 'Azure subscription 1 (b7a31e2a-65b9-4c9d-90df-6dc6a8301e24)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd terraform

          terraform plan -input=false -out=tfplan

    - publish: terraform/tfplan
      artifact: tfplan