trigger:
branches:
include:
- dev
- test
- main

pr: none

pool:
vmImage: 'ubuntu-latest'

stages:

* stage: Terraform_Plan
  displayName: 'Terraform Plan'

  jobs:

  * job: TerraformPlan
    displayName: 'Terraform Plan'

    steps:

    * checkout: self

    * bash: |
      set -e

      TERRAFORM_VERSION="1.9.8"

      curl -sSL -o terraform.zip 
      https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

      unzip -o terraform.zip

      sudo mv terraform /usr/local/bin/terraform

      terraform version
      displayName: 'Install Terraform'

    * task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
      azureSubscription: 'Azure subscription 1 (b7a31e2a-65b9-4c9d-90df-6dc6a8301e24)'
      addSpnToEnvironment: true
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |

      ```
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_TENANT_ID=$tenantId
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

      cd terraform

      terraform init -input=false
      ```

    * task: AzureCLI@2
      displayName: 'Terraform Validate'
      inputs:
      azureSubscription: 'Azure subscription 1 (b7a31e2a-65b9-4c9d-90df-6dc6a8301e24)'
      addSpnToEnvironment: true
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |

      ```
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_TENANT_ID=$tenantId
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

      cd terraform

      terraform validate
      ```

    * task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
      azureSubscription: 'Azure subscription 1 (b7a31e2a-65b9-4c9d-90df-6dc6a8301e24)'
      addSpnToEnvironment: true
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |

      ```
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_TENANT_ID=$tenantId
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

      cd terraform

      terraform plan -input=false -out=tfplan
      ```

    * publish: terraform/tfplan
      artifact: tfplan
      displayName: 'Publish Terraform Plan'
