parameters:
  - name: stageName
    type: string
  - name: environmentName
    type: string
  - name: appServiceName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: branchCondition
    type: string

stages:
  - stage: ${{ parameters.stageName }}
    displayName: Deploy ${{ parameters.environmentName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: eq(variables['Build.SourceBranch'], ${{ parameters.branchCondition }})
    jobs:
      - deployment: Deploy${{ parameters.environmentName }}
        environment: ${{ parameters.environmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Deploy ${{ parameters.environmentName }}
                  inputs:
                    azureSubscription: weatherappres-acr-service-connection
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az webapp config container set \
                        --name ${{ parameters.appServiceName }} \
                        --resource-group $(resourceGroup) \
                        --docker-custom-image-name $(containerRegistry)/$(imageRepository):$(imageTag)

