name: SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: Analyze (SonarCloud)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: |
          npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

          echo "Checking LCOV output..."
          if [ ! -f coverage/weather/lcov.info ]; then
            echo "ERROR: coverage/weather/lcov.info not found. Listing coverage dir:";
            ls -R coverage || true;
            exit 1;
          fi
        env:
          CI: true

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.coverage.exclusions=**/node_modules/**
            -Dsonar.inclusions=src/**
            -Dsonar.javascript.lcov.reportPaths=coverage/weather/lcov.info
            -Dsonar.coverage.exclusions=**/node_modules/**

